### ISSUE TITLE
run under wsl

### ISSUE THREAD

**Issue by vivkvv** [plynx-team/plynx#176]
I try to run due to an instruction:

git clone https://github.com/plynx-team/plynx.git
cd plynx
cp template_config.yaml config.yaml
make up       

But got as follows:

GitHub/plynx$ make up
mkdir -p ./data/resources
python -m webbrowser "http://localhost:3001/"

docker-compose -f ./docker-compose.yml up --scale workers=1
Starting mongodb ... done
Starting api     ... done
Starting frontend        ... done
Starting plynx_workers_1 ... done
Starting master          ... done
Attaching to mongodb, api, frontend, master, plynx_workers_1
api         | CRITICAL:root:Using config `config.yaml`
tcgetpgrp failed: Not a tty
master      | CRITICAL:root:Using config `config.yaml`
workers_1   | CRITICAL:root:Using config `config.yaml`
api         | /usr/local/lib/python3.8/site-packages/paramiko/transport.py:208: CryptographyDeprecationWarning: Blowfish has been deprecated
api         |   "class": algorithms.Blowfish,
api         | INFO:root:Using default IAM policies for new users: {'CAN_VIEW_OTHERS_OPERATIONS', 'IS_ADMIN', 'CAN_MODIFY_OTHERS_WORKFLOWS', 'CAN_CREATE_OPERATIONS', 'CAN_VIEW_OTHERS_WORKFLOWS', 'CAN_CREATE_WORKFLOWS', 'CAN_RUN_WORKFLOWS', 'CAN_VIEW_WORKFLOWS', 'CAN_VIEW_OPERATIONS'}
api         | INFO:root:Try db connection
mongodb exited with code 14
master      | /usr/local/lib/python3.8/site-packages/paramiko/transport.py:208: CryptographyDeprecationWarning: Blowfish has been deprecated
master      |   "class": algorithms.Blowfish,
master      | INFO:root:Init Worker
master      | INFO:root:WorkerConfig(kinds=['basic-dag-workflow'], api='http://api:5005')
master      | INFO:root:Start serving
master      | INFO:root:Exit _run_db_status_update
master      | Exception in thread Thread-1:
master      | Traceback (most recent call last):
master      |   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
master      | INFO:root:Exit _run_worker_state_update
master      |     conn = connection.create_connection(
Stopping api             ... done
GitHub/plynx$
master      |   File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
master      | Exception in thread Thread-2:
master      | Traceback (most recent call last):
master      |   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
master      |     sock.connect(sa)
master      | ConnectionRefusedError: [Errno 111] Connection refused
master      |

and so on

Is it my problem?

**Comment by khaxis** [comment]
Hello, can you please try the following change?
```
diff --git a/docker-compose.yml b/docker-compose.yml
index 57d0180..67fa083 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -7,7 +7,7 @@ services:
             - MONGO_DATA_DIR=/data/db
             - MONGO_LOG_DIR=/dev/null
         volumes:
-            - ./data/db:/data/db
+            - mongodata:/data/db
         ports:
             - 27017:27017
         command: mongod --logpath=/dev/null # --quiet
@@ -70,3 +70,6 @@ services:
             - api
         links:
             - api
+
+volumes:
+    mongodata:
```

It's a patch, so you save the content in a file a type `git apply <filename>`

**Comment by khaxis** [comment]
this is my full docker-compose.yml file:
```
version: "3.3"
services:
    mongodb:
        image: mongo:4.2.8
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - mongodata:/data/db
        ports:
            - 27017:27017
        command: mongod --logpath=/dev/null # --quiet

    master:
        image: plynxteam/backend:latest
        container_name: "master"
        depends_on:
            - mongodb
            - api
        links:
            - mongodb
            - api
        volumes:
            - ./data:/data
            - ./config.yaml:/app/config.yaml
        environment:
            - PLYNX_CONFIG=/app/config.yaml
        command: plynx worker -vvv -e basic-dag-workflow --internal-endpoint http://api:5005/plynx/api/v0
        restart: always

    workers:
        image: plynxteam/backend:latest
        depends_on:
            - mongodb
            - api
        links:
            - mongodb
            - api
        volumes:
            - ./data:/data
            - ./config.yaml:/app/config.yaml
        environment:
            - PLYNX_CONFIG=/app/config.yaml
        command: plynx worker -vvv -e basic-bash-jinja2-operation -e basic-python-node-operation -e basic-dag-operation -e python-workflow --internal-endpoint http://api:5005/plynx/api/v0
        restart: always

    api:
        image: plynxteam/backend:latest
        container_name: "api"
        ports:
            - "5005:5005"
        depends_on:
            - mongodb
        links:
            - mongodb
        volumes:
            - ./data:/data
            - ./config.yaml:/app/config.yaml
        environment:
            - PLYNX_CONFIG=/app/config.yaml
        command: plynx api -vvv

    frontend:
        image: plynxteam/ui:latest
        container_name: "frontend"
        ports:
            - "3001:80"
        depends_on:
            - api
        links:
            - api

volumes:
    mongodata:
```
